//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerManagementSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribution
    {
        public int Distribute_Id { get; set; }
        public int Collect_Id { get; set; }
        public int Emp_Id { get; set; }
        public System.DateTime Distribution_Time { get; set; }
    
        public virtual CollectRequest CollectRequest { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
