//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HungerManagementSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FoodManagementEntities2 : DbContext
    {
        public FoodManagementEntities2()
            : base("name=FoodManagementEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CollectRequest> CollectRequests { get; set; }
        public virtual DbSet<Distribution> Distributions { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FoodItem> FoodItems { get; set; }
        public virtual DbSet<NGO> NGOes { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
    }
}
